name: "Create a check with a status on a PR"

inputs:
  token:
    description: Github token"
    required: true
  pr:
    description: "PR number"
    required: true
  sha:
    description: "SHA of the commit to create the check on"
    required: true

runs:
  using: "node16"
  main: "dist/index.cjs"
