name: "js / test"

on:
  workflow_run:
    workflows: [workflow-trigger]
    types:
      - completed

permissions:
  statuses: write

jobs:
  get_pr:
    name: "Test one"
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.pr.outputs.pr_number }}
      source_repo: ${{ steps.pr.outputs.source_repo }}
      source_branch: ${{ steps.pr.outputs.source_branch }}
    steps:
      - id: pr
        uses: "gradio-app/github/actions/find-pr@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.pr.outputs.source_repo }}
          ref: ${{ steps.pr.outputs.source_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Print PR number"
        run: echo ${{ steps.pr.outputs.pr_number }}
      - name: "Print source repo"
        run: echo ${{ steps.pr.outputs.source_repo }}
      - name: "Print source branch"
        run: echo ${{ steps.pr.outputs.source_branch }}
      - name: "Print SHA"
        run: echo ${{ steps.pr.outputs.sha }}
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.pr.outputs.pr_number }}
          sha: ${{ steps.pr.outputs.sha }}
