name: Comment on pull request without race conditions

on:
  workflow_call:
    inputs:
      pr_number:
        type: string
      message:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: "previews"
      additional_text:
        required: false
        type: string
        default: ""
    secrets:
      gh_token:
        required: true

# jobs:
#   comment:
#     concurrency:
#       group: ${{inputs.pr_number || inputs.tag}}
#     runs-on: ubuntu-latest
#     steps:
#       - name: comment on pr
#         uses: "gradio-app/github/actions/comment-pr@main"
#         with:
#           gh_token: ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ inputs.tag }}
#           pr_number: ${{ inputs.pr_number}}
#           message: ${{ inputs.message }}
#           additional_text: ${{ inputs.additional_text }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: "Get PR number"
        id: pr
        uses: "gradio-app/github/actions/find-pr@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.pr.outputs.source_repo }}
          ref: ${{ steps.pr.outputs.source_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.pr.outputs.pr_number }}
          sha: ${{ steps.pr.outputs.sha }}
          name: "test / python ${{ matrix.python-version }}"
          result: "pending"
