name: workflow-run

on:
  workflow_run:
    workflows: [python/test]

permissions:
  statuses: write

jobs:
  trigger:
    name: "Trigger"
    runs-on: ubuntu-latest
    steps:
      - name: Upload data
        uses: actions/download-artifact@v2

        with:
          name: pr-data-${{ github.event.workflow_run.id }}
          path: metadata.json
      - name: "set metadata.json as output"
        id: pr
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const data = require("./metadata.json");
            return {
              pr_number: data.pr_number,
              source_repo: data.source_repo,
              source_branch: data.source_branch,
            }

      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.pr.outputs.source_repo }}
          ref: ${{ steps.pr.outputs.source_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Print PR number"
        run: echo ${{ steps.pr.outputs.pr_number }}
      - name: "Print source repo"
        run: echo ${{ steps.pr.outputs.source_repo }}
      - name: "Print source branch"
        run: echo ${{ steps.pr.outputs.source_branch }}
      - name: do check
        uses: "./.github/actions/do-check"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.pr.outputs.pr_number }}
