name: "test / python {version}"
on:
  workflow_run:
    workflows: [workflow-trigger]
    types:
      - requested
permissions:
  statuses: write

jobs:
  # prepare:
  #   name: "Test two"
  #   runs-on: ubuntu-latest
  #   outputs:
  #     source_repo: ${{ steps.pr.outputs.source_repo }}
  #     source_branch: ${{ steps.pr.outputs.source_branch }}
  #     pr_number: ${{ steps.pr.outputs.pr_number }}
  #     sha: ${{ steps.pr.outputs.sha }}
  #   steps:
  #     - name: "Get PR number"
  #       id: pr
  #       uses: "gradio-app/github/actions/find-pr@main"
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: ${{ steps.pr.outputs.source_repo }}
  #         ref: ${{ steps.pr.outputs.source_branch }}
  #         fetch-depth: 0
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: error
  #       run: exit 1
  #     - name: do check
  #       if: always()
  #       uses: "./.github/actions/do-check"
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         pr: ${{ steps.pr.outputs.pr_number }}
  #         sha: ${{ steps.pr.outputs.sha }}
  #         name: "test / python ${{ matrix.python-version }}"
  #         result: "pending"
  test-python:
    name: "Test two"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - name: Call Composite Action
        id: prepare
        uses: ./.github/actions/prepare
        with:
          name: "test / python ${{ matrix.python-version }}"
      - name: error
        if: matrix.python-version == '3.8'
        run: exit 1
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.prepare.outputs.pr_number }}
          sha: ${{ steps.prepare.outputs.sha }}
          name: "test / python ${{ matrix.python-version }}"
          result: ${{ job.status }}
