name: "test / python {version}"
on: release

permissions:
  statuses: write

jobs:
  prepare:
    name: "Test two"
    runs-on: ubuntu-latest
    outputs:
      source_repo: ${{ steps.pr.outputs.source_repo }}
      source_branch: ${{ steps.pr.outputs.source_branch }}
      pr_number: ${{ steps.pr.outputs.pr_number }}
      sha: ${{ steps.pr.outputs.sha }}
    steps:
      - name: "Get PR number"
        id: pr
        uses: "gradio-app/github/actions/find-pr@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.pr.outputs.source_repo }}
          ref: ${{ steps.pr.outputs.source_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: error
        run: exit 1
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.pr.outputs.pr_number }}
          sha: ${{ steps.pr.outputs.sha }}
          name: "test / python {version}"
  test-python:
    name: "Test two"
    runs-on: ubuntu-latest
    steps:
      - name: "Get PR number"
        id: pr
        uses: "gradio-app/github/actions/find-pr@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          repository: ${{ steps.pr.outputs.source_repo }}
          ref: ${{ steps.pr.outputs.source_branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: error
        run: exit 1
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ steps.pr.outputs.pr_number }}
          sha: ${{ steps.pr.outputs.sha }}
