name: "test / js"
on:
  workflow_run:
    workflows: [trigger]
    types:
      - requested
permissions:
  statuses: write

jobs:
  changes:
    name: "changes"
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.changes.outputs.should_run }}
      sha: ${{ steps.changes.outputs.sha }}
      pr_number: ${{ steps.changes.outputs.pr_number }}
      source_branch: ${{ steps.changes.outputs.source_branch }}
      source_repo: ${{ steps.changes.outputs.source_repo }}
      run_windows: ${{ steps.check-labels.outputs.run_windows }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/changes
        id: changes
        with:
          type: "js"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check for labels and save to output
        run: echo "run_windows=$(gh pr view ${{ steps.changes.outputs.pr_number }} --json labels --jq '.labels | map(.name) | contains(["bug"])')" >> $GITHUB_OUTPUT
        id: check-labels
      - name: print output
        run: echo "${{ toJson(steps) }}"

  test-js:
    name: "test-js"
    runs-on: ubuntu-latest
    needs: changes

    if: needs.changes.outputs.should_run == 'true'
    steps:
      - name: echo concurrency group
        run: echo "${{ github.event.workflow_run.event}}-${{ github.event.workflow_run.head_branch}}"
      - name: echo github context
        run: echo "${{ toJson(github) }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.changes.outputs.source_branch }}
          repository: ${{ needs.changes.outputs.source_repo }}

      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ needs.changes.outputs.pr_number }}
          sha: ${{ needs.changes.outputs.sha }}
          name: "test / js"
          result: ${{ job.status }}
          job_id: "test-js"
