name: "test / client / python"
on:
  workflow_run:
    workflows: [trigger]
    types:
      - requested
permissions:
  statuses: write

jobs:
  changes:
    name: "Check for changes"
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.changes.outputs.should_run }}
      sha: ${{ steps.changes.outputs.sha }}
      pr_number: ${{ steps.changes.outputs.pr_number }}
      source_branch: ${{ steps.changes.outputs.source_branch }}
      source_repo: ${{ steps.changes.outputs.source_repo }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/changes
        id: changes
        with:
          type: "python-client"
          token: ${{ secrets.GITHUB_TOKEN }}

  test-python:
    name: "test-python-client-${{matrix.python-version}}"
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_run == 'true'
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.changes.outputs.source_branch }}
          repository: ${{ needs.changes.outputs.source_repo }}
      - name: do check
        if: always()
        uses: "./.github/actions/do-check"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr: ${{ needs.changes.outputs.pr_number }}
          sha: ${{ needs.changes.outputs.sha }}
          name: "test / client / python ${{ matrix.python-version }}"
          result: ${{ job.status }}
          job_id: "test-python-client-${{matrix.python-version}}"
