name: trigger
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: workflows
    runs-on: ubuntu-22.04
    steps:
      - name: echo context as formatted json
        run: echo '${{ toJson(github) }}'

      - run: echo "Hello, github!"
