name: workflow-trigger
on:
  push:
    branches:
      - main
  pull_request:
    # types: [opened, synchronize, reopened, edited, labeled, unlabeled]
    branches:
      - main
  # issue_comment:
  #   types: [edited]

jobs:
  build:
    name: trigger
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Hello, world!"
